---
hero_image: images/tetris-theme.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Codeer het Tetris thema
description: Programmeer Sonic Pi om muzieknoten te spelen en het Tetris-thema te maken.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/tetris-theme
interests: music
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - title: Inleiding
  - title: Codeer het begin
  - title: 'Uitdaging: Maak de melodie af'
  - title: Sneller!
  - title: 'Uitdaging: Mix de melodie'
  - title: 'Uitdaging: Meer van de melodie'
  - title: 'Uitdaging: Meer muziek'
