---
hero_image: images/banner.png
theme: red
duration: 1
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Code the Tetris Theme Tune
description: Program Sonic Pi to play musical notes and create the Tetris theme tune.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/tetris-theme
interests: music/sound
technologies: ''
site_areas: codeclub, sonic-pi
steps:
- title: Introduction
- title: Code the Beginning
- title: 'Challenge: Finish the tune'
- title: Faster!
- title: 'Challenge: Mix the tune'
- title: 'Challenge: More of the tune'
- title: 'Challenge: More music'

