---
hero_image: images/tetris-theme.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Tetris Theme (टेट्रिस थीम) धुन को कोड करना
description: संगीत के सुर बजाने और टेट्रिस थीम ट्यून बनाने के लिए Sonic Pi को प्रोग्राम
  करना।
original_url: https://codeclubprojects.org/en-GB/sonic-pi/tetris-theme
interests: music
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: परिचय
  completion: engaged
- title: आरंभ कोड करना
- title: 'चुनौती: धुन समाप्त करना'
- title: अधिक तेज़!
- title: 'चुनौती: धुन को मिलाना'
- title: 'चुनौती: धुन के बारे में और अधिक'
  completion: internal
- title: 'चुनौती: अधिक संगीत'
