---
hero_image: images/tetris-theme.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Skab Tetris Sangen med Kode
description: Programmer Sonic Pi til at spille musiknoder og skabe Tetris theme sangen.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/tetris-theme
interests: music
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - title: Introduktion
  - title: Programmer begyndelsen
  - title: 'Udfordring: Afslut melodien'
  - title: Hurtigere!
  - title: 'Udfordring: Mix melodien'
  - title: 'Udfordring: Mere af melodien'
  - title: 'Udfordring: Mere musik'
