---
hero_image: images/tetris-theme.png
theme: punainen
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Code the Tetris Theme Tune
description: Program Sonic Pi to play musical notes and create the Tetris theme tune.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/tetris-theme
interests: musiikki
technologies: ''
site_areas: projektit
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Johdanto
  - 
    title: Code the Beginning
  - 
    title: 'Challenge: Finish the tune'
  - 
    title: Faster!
  - 
    title: 'Challenge: Mix the tune'
  - 
    title: 'Challenge: More of the tune'
  - 
    title: 'Challenge: More music'
