---
hero_image: images/tetris-theme.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Kodieren Sie das Tetris Theme Tune
description: Programmieren Sie Sonic Pi, um Musiknoten zu spielen, und erstellen Sie die Tetris-Melodie.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/tetris-theme
interests: musik
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Code den Anfang
  - 
    title: 'Herausforderung: Beende das Stück'
  - 
    title: Schneller!
  - 
    title: 'Herausforderung: Mischen Sie die Melodie'
  - 
    title: 'Herausforderung: Mehr von der Melodie'
  - 
    title: 'Herausforderung: Mehr Musik'
