---
hero_image: images / tetris-theme.png
theme: vermell
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, disseny-0, programació-1, phys-comp-0, fabricació-0, comunitat-0
title: Code the Tetris Theme Tune
description: Program Sonic Pi to play musical notes and create the Tetris theme tune.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/tetris-theme
interests: música
technologies: ''
site_areas: projectes
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducció
  - 
    title: Code the Beginning
  - 
    title: 'Challenge: Finish the tune'
  - 
    title: Faster!
  - 
    title: 'Challenge: Mix the tune'
  - 
    title: 'Challenge: More of the tune'
  - 
    title: 'Challenge: More music'
