---
hero_image: images/tetris-theme.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Codifica el tema musical de Tetris
description: Programa Sonic Pi para reproducir notas musicales y crear el tema Tetris.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/tetris-theme
interests: music
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: Introducción
  completion: engaged
- title: Programar el inicio
- title: 'Desafío: Termina la melodía'
- title: "¡Más rápido!"
- title: 'Desafío: Mezclar la melodía'
- title: 'Desafío: Más de la melodía'
  completion: internal
- title: 'Desafío: Más música'
