---
hero_image: images/tetris-theme.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: برمج تونة ثيم تيتريس
description: برمج Sonic Pi لتشغيل النغمات الموسيقية وانشاء ثيم تيتريس.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/tetris-theme
interests: music
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - title: المقدمة
  - title: برمجة البدء
  - title: 'التحدي: أكمل اللحن'
  - title: أسرع!
  - title: 'التحدي: امزج اللحن'
  - title: 'التحدي: المزيد من اللحن'
  - title: 'التحدي: المزيد من الموسيقى'