---
hero_image: images/tetris-theme.png
theme: 빨간
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, 디자인 -0, 프로그래밍 -1, phys-comp-0, 제조 -0, 커뮤니티 -0
title: Code the Tetris Theme Tune
description: Program Sonic Pi to play musical notes and create the Tetris theme tune.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/tetris-theme
interests: 음악
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 소개
  - 
    title: Code the Beginning
  - 
    title: 'Challenge: Finish the tune'
  - 
    title: Faster!
  - 
    title: 'Challenge: Mix the tune'
  - 
    title: 'Challenge: More of the tune'
  - 
    title: 'Challenge: More music'
